### ISSUE TITLE
`vayu pomo` panics

### ISSUE THREAD

**Issue by datdenkikniet** [MythicalCow/vayu#1]
When running `vayu pomo` with an incorrect amount of arguments causes the program to panic on the latest version (v0.1.6).

Stack trace:

```shell
$ RUST_BACKTRACE=1 cargo run -- pomo 
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/vayu pomo`
thread 'main' panicked at src/main.rs:302:42:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: Empty }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1077:23
   4: vayu::pomodoro
             at ./src/main.rs:302:22
   5: vayu::main
             at ./src/main.rs:150:9
   6: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```

**Comment by MythicalCow** [comment]
hi! thanks for raising this issue. I will release a bug fix tonight

**Comment by datdenkikniet** [comment]
`clap`'s derive macro also [supports subcommands][1] so you don't have to do as much manual argument validation. Can highly recommend it. Will also make the help menu much more usable, assuming you provide nice doc comments for it.

[1]: https://docs.rs/clap/latest/clap/_derive/_tutorial/chapter_0/index.html

**Comment by simonsan** [comment]
Yes, what datdenkikniet says is important, also I would always recommend abscissa ( https://github.com/iqlusioninc/abscissa ) for these kinda things, that get more complex than a single command in the CLI. It enforces good patterns to develop CLIs.
